# Generated by Django 4.0.1 on 2022-03-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reader',
        ),
    ]
