# Generated by Django 4.0.1 on 2022-03-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_user_reader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
