# Generated by Django 4.0.1 on 2022-03-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_user_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
