# Generated by Django 4.0.1 on 2022-04-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_delete_bookey_rename_totalratings_book_totalreviews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
