# Generated by Django 4.0.1 on 2022-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_delete_genre_book_author_book_bookformat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
