# Generated by Django 4.0.1 on 2022-04-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_book_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
