# Generated by Django 4.0.1 on 2022-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
