# Generated by Django 4.0.1 on 2022-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
