# Generated by Django 4.0.1 on 2022-04-14 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0040_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
