# Generated by Django 4.0.1 on 2022-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_book_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=b'I01\n'),
        ),
    ]
