# Generated by Django 4.0.1 on 2022-04-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_alter_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='wishlist',
        ),
    ]
