# Generated by Django 4.0.1 on 2022-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_book_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=b'I01\n')),
            ],
        ),
    ]
