# Generated by Django 4.0.1 on 2022-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_main_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.ManyToManyField(related_name='main_genre', to='App.Main_Genre'),
        ),
    ]
