# Generated by Django 4.0.1 on 2022-07-08 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_remove_genre_title_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='main_category',
            field=models.ManyToManyField(related_name='main_genre', to='App.Main_Genre'),
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
