# Generated by Django 4.0.1 on 2022-07-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_genre_main_category_remove_genre_title_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
