# Generated by Django 4.0.1 on 2022-07-08 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_alter_main_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='main_category',
        ),
        migrations.AddField(
            model_name='genre',
            name='main_category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='App.main_genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='main_genre',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=b'I01\n'),
            preserve_default=False,
        ),
    ]
