# Generated by Django 4.0.1 on 2022-07-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_alter_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='main_category',
        ),
    ]
