# Generated by Django 4.0.1 on 2022-07-08 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_remove_genre_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=b'I01\n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main_genre',
            name='title',
            field=models.CharField(max_length=50, unique=b'I01\n'),
        ),
    ]
