# Generated by Django 4.0.1 on 2022-07-08 03:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_alter_genre_title_alter_main_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='main_category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='App.main_genre'),
            preserve_default=False,
        ),
    ]
