# Generated by Django 4.0.1 on 2022-07-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0059_remove_genre_main_category_genre_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='main_category',
        ),
    ]
