# Generated by Django 4.0.1 on 2022-07-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_remove_genre_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_genre',
            old_name='title',
            new_name='name',
        ),
    ]
