# Generated by Django 4.0.1 on 2022-07-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_rename_title_main_genre_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Genre',
        ),
    ]
