# Generated by Django 4.0.1 on 2022-07-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0062_delete_main_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=b'I01\n')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.ManyToManyField(related_name='category', to='App.Category'),
        ),
    ]
