# Generated by Django 4.0.1 on 2022-07-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_remove_genre_category_genre_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
