# Generated by Django 4.0.1 on 2022-07-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
